#!/usr/bin/python3
from sys import argv
def factorize(value):
    num = 2

    if value < 2:
        return
    print()
    print(value, "<- value-bef")
    while value % num:
        num += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / num, num))
    print(value, "<- value-aft")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        j = file.readline()

        while j != "":
            value = int(j.split('\n')[0])
            factorize(value)  # Corrected the variable name
            j = file.readline()
except:
    pass
