#!/usr/bin/python3
from sys import argv

def factorize(value):
    i = 2

    if value < 2:
        return

    print()
    print(value, "<- value-before")
    
    while value % i:
        i += 1

    print("{:.0f} = {:.0f} * {:.0f}".format(value, value / i, i))
    
    print(value, "<- value-after")
    print()

if len(argv) != 2:
    exit("Usage: {} <input_file>".format(argv[0]))

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.strip())
            factorize(value)
            line = file.readline()

except FileNotFoundError:
    exit("Error: File not found.")
except ValueError:
    exit("Error: Invalid data in the file.")